### ISSUE TITLE
New feature: format bytes 

### ISSUE THREAD

**Issue by silviucpp** [DOBRO/uef-lib#1]
Hello,

Looking to you awesome lib I saw that might be room also for a function to format the bytes in KB, MB, TB and so on.

Silviu

**Comment by DOBRO** [comment]
Hi, 

I don't see any difficulties with that :) We should think about the proper return value. There are several possible ways. For example, 
"123KB", 
{123, kb},
...

any thoughts?

**Comment by DOBRO** [comment]
... or you mean something like:

format_bytes(2000, kb) -> 1
format_bytes(2000, mb) -> 0
?

**Comment by silviucpp** [comment]
No no . First option where do you provide the number of bytes and returns a binary like <<"123 KB">>.

Silviu

**Comment by silviucpp** [comment]
Probably should allow you to specify if you want to use SI or Binary mode.
https://en.wikipedia.org/wiki/Megabyte in SI mode (International System of Units) one KB is 1000 bytes. In bynary mode is 1024.

**Comment by DOBRO** [comment]
Since the function carries the meaning of formatting, it should provide an opportunity to choose the output format. Say, I want to get it in megabytes (not in kilobytes, even if the input value is too small), it should return, for example, <<"0 MB">>.
It also may have the option 'auto' and you leave the function to decide what to return itself.

For example:
format_bytes(1024, mb) -> <<"0 MB">>
format_bytes(1024, kb) -> <<"1 KB">>
format_bytes(1024, auto) -> <<"1 KB">>

But what if I want to get it in integer, not in binary? We are coming to one more option.

So, the options so far:
- 1000 or 1024 base;
- specified units (KB, MB, ...) or 'auto'
- output data type (integer, binary, string)

Next, if the output format is binary/string, should it add units (KB, MB, ...)? And if it should, then where (prefixed or appended)?

**Comment by silviucpp** [comment]
I agree with you on all the options. Regarding "Next, if the output format is binary/string, should it add units (KB, MB, ...)? And if it should, then where (prefixed or appended)?" I think should add the unit at the end.. In case somebody doesn't like can anytime use : as output integer and function should return something like:
`{value, unit}` and then he can do the formatting. I think it's important to return the unit for `integer` because in case of `auto` the calling process will know now what unit was picked.

**Comment by DOBRO** [comment]
Ok, looking forward...

**Comment by DOBRO** [comment]
Functions added. Possible ways to call:

```erlang
uef_format:format_bytes(Bytes).

uef_format:format_bytes(Bytes, #{units => Units, type => Type, base => Base}).
```
where:
```erlang
Units :: auto | 'KB' | 'MB' | 'GB' | 'TB' | 'PB' | 'EB' | 'ZB' | 'YB',
Type :: bin | int,
Base :: 2 | 10. % 2 means 1024, 10 means 1000.
```
I will add more tests and docs later.

**Comment by silviucpp** [comment]
hmm instead type maybe a better name is output_type or something similar.

**Comment by DOBRO** [comment]
`datatype` ?

**Comment by DOBRO** [comment]
or `to_type`

**Comment by silviucpp** [comment]
What I mean is that #{units => Units, type => Type, base => Base}, `type` indicates how the output is generated : as binary or integer. and I think you can put a better name rather than `type`.

**Comment by DOBRO** [comment]
It was understood. And I suggested two variants: `datatype` and `to_type`.
`output_type` is longer but more clear. If you prefer this, I can commit it.

**Comment by silviucpp** [comment]
I think `output_type` it's ok. also `to_type`. it's your call.
Silviu

**Comment by DOBRO** [comment]
Done. Version updated

**Comment by silviucpp** [comment]
I'm thinking if instead: <<"1MB">> better to format like: <<"1 MB">> . (a space between value and unit).

**Comment by DOBRO** [comment]
Separator added as option, see README. The default is `<<>>` (empty binary).
